### ISSUE TITLE
It works only with GPU

### ISSUE THREAD

**Issue by tommasogiannantonio** [MLResearchAtOSRAM/tmm_fast#6]
Hi, if I try to run the demo script `example_tmm.py` in a CPU-only environment, the following error appears:
`AssertionError: It's not clear which beam is incoming vs outgoing. Weird index maybe?`

Is there any suggested fix or workaround? Thanks!

**Comment by MLResearchAtOSRAM** [comment]
This error typically appears when the first or the last layer has a complex refractive index. Unfortunately, this is a limitation of the transfer matrix and not a bug in the software.
Can you show me an example of layer thicknesses and refractive index for which the error appears?
